name: ExcellentKillStreaks
version: 'v1.4.0'
main: dragon.me.excellentKillStreaks.ExcellentKillStreaks
api-version: '1.21'
description: "A lightweight killstreak system for all kinds of Paper servers."
authors:
  - DragonDevelopsStuff
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      # This means that your plugin will not have access to their classpath
      join-classpath: true
